const SUPABASE_URL='https://jpnwqoghmxpheotlstxx.supabase.co';
const SUPABASE_KEY='sb_publishable_2rqvTatoYZmq85T5RDUiAA_3cbMW1Rm';
const sb=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const rates={followers:4500,likes:800,views:1200};
const serviceName={followers:'Followers',likes:'Likes',views:'Views'};
let state={session:null,profile:null,orders:[],balance:0,customers:[],adminOrders:[],view:'home'};
const app=document.getElementById('app');
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const money=n=>'₦'+Number(n||0).toLocaleString();
function shell(content){return `<div class="wrap"><header class="top"><div class="brand"><div class="mark">BTB</div><div><div class="eyebrow">BEYOND THE BINARY</div><h1>BOOST HUB</h1></div></div><div>${state.session?`<button class="pill" onclick="logout()">Sign out</button>`:`<button class="pill" onclick="showAuth('login')">Sign in</button>`}</div></header>${content}<footer>BEYOND THE BINARY MEDIA • BOOST HUB</footer></div>`}
function authForm(mode){const login=mode==='login';return shell(`<section class="card auth"><div class="title"><div class="num">${login?'01':'00'}</div><div><h3>${login?'Welcome back':'Create your account'}</h3><p>${login?'Sign in to manage your boost orders.':'Register once to place and track orders.'}</p></div></div><form onsubmit="submitAuth(event,'${mode}')">${!login?'<label>Display name</label><input id="name" required placeholder="Your name">':''}<label>Email</label><input id="email" type="email" required placeholder="you@example.com"><label>Password</label><div class="password-wrap"><input id="password" type="password" minlength="6" required placeholder="At least 6 characters"><button type="button" class="password-toggle" onclick="const p=document.getElementById('password');p.type=p.type==='password'?'text':'password';this.textContent=p.type==='password'?'👁️':'🙈'">👁️</button></div><button class="btn" type="submit">${login?'Sign in':'Create account'}</button></form><div id="authmsg"></div><p class="hint" style="margin-top:14px">${login?'New here?':'Already have an account?'} <button class="tab" onclick="showAuth('${login?'register':'login'}')">${login?'Create account':'Sign in'}</button></p></section>`) }
function showAuth(mode){app.innerHTML=authForm(mode)}
async function submitAuth(e,mode){e.preventDefault();const msg=document.getElementById('authmsg');msg.innerHTML='';try{const emailEl=document.getElementById('email');const passwordEl=document.getElementById('password');const nameEl=document.getElementById('name');const emailValue=emailEl?.value?.trim()||'';const passwordValue=passwordEl?.value||'';const displayName=nameEl?.value?.trim()||'';let r;if(mode==='login')r=await sb.auth.signInWithPassword({email:emailValue,password:passwordValue});else r=await sb.auth.signUp({email:emailValue,password:passwordValue,options:{data:{display_name:displayName}}});if(r.error)throw r.error;if(mode==='register'&&!r.data.session){msg.innerHTML='<p class="status">Account created. Check your email to confirm, then sign in.</p>';return}await refresh();}catch(x){msg.innerHTML=`<p class="error">${esc(x.message)}</p>`}}
async function refresh(){const {data:{session}}=await sb.auth.getSession();state.session=session;state.profile=null;if(session){let p=await sb.from('users').select('*').eq('auth_user_id',session.user.id).single();if(p.error)console.warn(p.error);state.profile=p.data||null;await loadOrders();}render()}
async function loadOrders(){if(!state.profile)return;const [o,w]=await Promise.all([sb.from('boost_orders').select('*').eq('user_id',state.profile.id).order('created_at',{ascending:false}),sb.from('wallet_transactions').select('amount_ngn').eq('user_id',state.profile.id)]);state.orders=o.data||[];state.balance=(w.data||[]).reduce((a,x)=>a+Number(x.amount_ngn||0),0);if(state.profile.role==='admin')await loadAdmin()}
async function loadAdmin(){const [u,o]=await Promise.all([sb.from('users').select('*').order('created_at',{ascending:false}),sb.from('boost_orders').select('*').order('created_at',{ascending:false})]);state.customers=u.data||[];state.adminOrders=o.data||[]}
function home(){const total=Math.round((rates.followers*1000)/1000);return shell(`<section class="hero"><small>SOCIAL PROMOTION</small><h2>Grow your social presence.<br><em>One order at a time.</em></h2><p>Choose your platform, paste the exact link, set your quantity and submit your order.</p></section>${!state.session?`<section class="card"><div class="title"><div class="num">00</div><div><h3>Account required</h3><p>Create an account or sign in before placing a boost order.</p></div></div><button class="btn" onclick="showAuth('register')">Create account</button> <button class="btn secondary" onclick="showAuth('login')">Log in</button></section>`:orderForm()}${state.session?`<section class="card history"><div class="title"><div class="num">03</div><div><h3>Order history</h3><p>Balance: <b>${money(state.balance)}</b></p></div></div>${ordersHtml(state.orders)}</section>`:''}`)}
function orderForm(){return `<div class="grid"><section class="card"><div class="title"><div class="num">01</div><div><h3>Build your order</h3><p>Tell us exactly where and what to deliver.</p></div></div><label>Social platform</label><select id="platform"><option>Instagram</option><option>TikTok</option><option>Facebook</option><option>Telegram</option><option>X</option></select><label>Service</label><select id="service" onchange="calc()"><option value="followers">Followers — ₦4,500 / 1,000</option><option value="likes">Likes — ₦800 / 1,000</option><option value="views">Views — ₦1,200 / 1,000</option></select><label>Social media link *</label><input id="link" type="url" required placeholder="https://instagram.com/yourprofile"><label>Quantity *</label><input id="quantity" type="number" min="1" step="1" value="1000" oninput="calc()"><div class="quick">${[500,1000,2500,5000].map(q=>`<button type="button" onclick="setQty(${q})">${q.toLocaleString()}</button>`).join('')}</div><p class="hint" style="margin-top:8px">Enter the exact number you want.</p><div class="total"><div><small>ORDER TOTAL</small><strong id="total">₦4,500</strong></div><button class="btn" onclick="placeOrder()">Continue</button></div><div id="orderMsg"></div></section><aside class="card"><div class="title"><div class="num">02</div><div><h3>Pay with OPay</h3><p>Use the account below for your order.</p></div></div><div class="payment"><small>OPAY ACCOUNT</small><strong>9165647651</strong><span>Justice Trust Ugoala</span></div><button class="btn secondary" onclick="navigator.clipboard?.writeText('9165647651')">Copy account number</button><div class="notice" style="margin-top:12px">After payment, your order remains <b>Awaiting verification</b> until payment is confirmed.</div></aside></div>`}
function calc(){const q=Number(document.getElementById('quantity')?.value||0),s=document.getElementById('service')?.value||'followers';const el=document.getElementById('total');if(el)el.textContent=money(Math.round(rates[s]*q/1000))}
function setQty(q){document.getElementById('quantity').value=q;calc()}
async function placeOrder(){const platform=document.getElementById('platform').value,service=document.getElementById('service').value,quantity=Number(document.getElementById('quantity').value),social_link=document.getElementById('link').value.trim(),msg=document.getElementById('orderMsg');if(!social_link||quantity<1){msg.innerHTML='<p class="error">Enter a valid link and quantity.</p>';return}const total=Math.round(rates[service]*quantity/1000);const {error}=await sb.from('boost_orders').insert({user_id:state.profile.id,platform,service,social_link,quantity,total_amount_ngn:total});if(error){msg.innerHTML=`<p class="error">${esc(error.message)}</p>`;return}msg.innerHTML=`<div class="status good" style="margin-top:12px">Order submitted — Awaiting verification. Pay ${money(total)} to OPay 9165647651 and keep your receipt.</div>`;await loadOrders();setTimeout(render,800)}
function ordersHtml(rows){if(!rows.length)return '<div class="empty">No orders yet.</div>';return rows.map(o=>`<div class="order"><div class="orderhead"><b>#${esc(o.id)} · ${esc(o.platform)} ${esc(serviceName[o.service]||o.service)}</b><b>${money(o.total_amount_ngn)}</b></div><small>${esc(o.social_link)} · Qty ${Number(o.quantity).toLocaleString()}</small><div class="status" style="margin-top:9px">${esc(o.status)} · payment ${esc(o.payment_status)}</div></div>`).join('')}
function admin(){return shell(`<section class="hero"><small>ADMIN CONTROL PANEL</small><h2>Manage Boost Hub.</h2><p>Review orders, verify payments and manage customer wallet balances.</p></section><div class="admin-grid"><section class="card"><div class="title"><div class="num">01</div><div><h3>Customers</h3><p>Current registered accounts.</p></div></div>${state.customers.map(c=>`<div class="customer"><div><b>${esc(c.display_name)}</b><br><small>${esc(c.email)}</small></div><div><b id="bal-${c.id}">—</b><br><button class="tab" onclick="addCredit(${c.id},${JSON.stringify(c.display_name)})">Add balance</button></div></div>`).join('')}</section><section class="card"><div class="title"><div class="num">02</div><div><h3>Orders</h3><p>Verify or reject customer payments.</p></div></div>${state.adminOrders.length?state.adminOrders.map(o=>`<div class="order"><div class="orderhead"><b>#${o.id} · ${esc(o.platform)}</b><b>${money(o.total_amount_ngn)}</b></div><small>User ${o.user_id} · ${esc(o.service)} · Qty ${Number(o.quantity).toLocaleString()}</small><p style="font-size:12px;word-break:break-all">${esc(o.social_link)}</p><div style="display:flex;gap:7px;flex-wrap:wrap"><button class="tab" onclick="updateOrder(${o.id},'verified','verified')">Verify payment</button><button class="tab" onclick="updateOrder(${o.id},'cancelled','rejected')">Reject</button><button class="tab" onclick="updateOrder(${o.id},'completed','verified')">Complete</button></div></div>`).join(''):'<div class="empty">No orders.</div>'}</section></div>`)}
async function addCredit(uid,name){const raw=prompt(`Enter wallet amount for ${name}. Use a positive number to add credit or a negative number to deduct.`);if(raw===null)return;const amount=Number(raw);if(!Number.isFinite(amount)||amount===0)return alert('Enter a valid amount.');const {error}=await sb.from('wallet_transactions').insert({user_id:uid,amount_ngn:Math.round(amount),transaction_type:amount>0?'admin_credit':'admin_debit',reference:'Admin adjustment'});if(error)alert(error.message);else{alert('Balance updated.');await loadOrders();render()}}
async function updateOrder(id,status,payment_status){const {error}=await sb.from('boost_orders').update({status,payment_status}).eq('id',id);if(error)alert(error.message);else{await loadOrders();render()}}
async function logout(){await sb.auth.signOut();await refresh()}
function render(){if(!state.session){if(app.dataset.auth==='1')return;app.innerHTML=home();return}app.dataset.auth='0';app.innerHTML=state.profile?.role==='admin'?admin():home();}
sb.auth.onAuthStateChange(()=>setTimeout(refresh,0));refresh();
